@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Librarian {
    -name
    -librarianID
}

class Author {
    -name
    -authorID
    -biography
    -photo
}

Librarian "1" -right-- "0..*" Author:  Register


@enduml